### ISSUE TITLE
Unable to build 2.9.9 using Carthage

### ISSUE THREAD

**Issue by siemensikkema** [mixpanel/mixpanel-iphone#490]
The issue has to do with the addition of the MPResource.* files. In it there is a reference to -[UIApplication sharedApplication] and this does not compile for the WatchOS target.

```
[PROJECT DIR]/Carthage/Checkouts/mixpanel-iphone/Mixpanel/MPResources.m:17:77: error: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
```

 Version 2.9.8 works fine.

**Comment by samgreen** [comment]
This is an oversight on our part. For a quick fix, if you're not actually building for watchOS, you can pass --platforms iOS

**Comment by Rupert-RR** [comment]
I get the same problem, and I'm already passing in `-platform ios`...

**Comment by siemensikkema** [comment]
Same here, I'm also passing in the that flag.

**Comment by fobin** [comment]
+1

**Comment by patedit** [comment]
Sorry for the inconvenience guys. You should be able to build 2.9.9 again. I've update the framework on 2.9.9 release with the fix (https://github.com/mixpanel/mixpanel-iphone/releases/tag/v2.9.9). Let me know if it works! Thanks!

**Comment by dkalachov** [comment]
@patedit, I got the same error, using 2.9.9 version.

```
$ carthage build mixpanel-iphone --platform iOS
*** xcodebuild output can be found in /var/folders/t6/5sstpp0d2459jmmdtvh0lg8r0000gn/T/carthage-xcodebuild.sTX7NW.log
*** Building scheme "Mixpanel-appExtension" in Mixpanel.xcodeproj
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/Kalachov/Library/Developer/Xcode/DerivedData/Mixpanel-fbjcmbdkqlbkzudpcmgayjxnrbvs/Build/Intermediates/Mixpanel.build/Release-iphoneos/MixpanelAppExtension.build/Objects-normal/armv7/MPResources.o Mixpanel/MPResources.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/Kalachov/Dev/pixellot-ios/Pixellot/Carthage/Checkouts/mixpanel-iphone/Mixpanel/MPResources.m:17:77: error: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
A shell task (/usr/bin/xcrun xcodebuild -project /Users/Kalachov/Dev/pixellot-ios/Pixellot/Carthage/Checkouts/mixpanel-iphone/Mixpanel.xcodeproj -scheme Mixpanel-appExtension -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/Kalachov/Library/Developer/Xcode/DerivedData/Mixpanel-fbjcmbdkqlbkzudpcmgayjxnrbvs/Build/Intermediates/Mixpanel.build/Release-iphoneos/MixpanelAppExtension.build/Objects-normal/armv7/MPResources.o Mixpanel/MPResources.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by siemensikkema** [comment]
@patedit Same here, even after removing the cached checkout from Carthage.

**Comment by patedit** [comment]
@siemensikkema @dkalachov Can I see your Cartfile? Are you guys running `carthage update` first? Have you tried to fetch the framework from `master`or `71a7f72152888e91fa62806a0285409d59b9e4c4`?

**Comment by dkalachov** [comment]
@patedit 
When I use **Cartfile** `github "mixpanel/mixpanel-iphone"` then **Cartfile.resolved** contains `github "mixpanel/mixpanel-iphone" "v2.9.9"` and build fails.

When I use **Cartfile** `github "mixpanel/mixpanel-iphone" "master"` then **Cartfile.resolved** contains `github "mixpanel/mixpanel-iphone" "71a7f72152888e91fa62806a0285409d59b9e4c4"` and build OK.

**Comment by patedit** [comment]
@dkalachov Thanks for the feedback! I have created a new tag `v2.9.9.001` and Carthage should automatically resolve the dependency and grab that one. `carthage update` should modify `Cartfile.resolved` this time and you should be good to go. Let me know if it worked.

**Comment by dkalachov** [comment]
@patedit Everything works great, thank you!
